name: Java CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
  
    # 2023-05-02 disabled because unit-test downloads from ivoa.net, which is down
    # - name: build and test caom2-dm
    #   run: cd caom2-dm && ../gradlew --info clean build xslt

    - name: build and test caom2
      run: cd caom2 && ../gradlew --info clean build javadoc checkstyleMain install
      
# caom2-compute depends on wcslib 
    - name: build and test caom2-compute
      run: cd caom2-compute && ../gradlew --info clean assemble javadoc checkstyleMain install
    
    - name: build and test caom2-artifact-resolvers
      run: cd caom2-artifact-resolvers && ../gradlew --info clean assemble javadoc checkstyleMain install

# no checkstyle for these utilities
    - name: build and test fits2caom2
      run: cd fits2caom2 && ../gradlew --info clean build javadoc install

    - name: build and test caom2-validator
      run: cd caom2-validator && ../gradlew --info clean build
    
    - name: build and test caom2-viz
      run: cd caom2-viz && ../gradlew --info clean build
